### ISSUE TITLE
Object locking

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop-clients#17]
### Summary
<table>
  <tr>
    <td><b>As an</b></td>
    <td>archivist</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       lock objects that go into glacier
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>be confident that they will not be deleted or overwritten</td>
  </tr>
</table>

### Tasks
- [x] Add a config value to turn object locking on/off
- [x] Set object locking on for files going into glacier

**Comment by JeffreyHuynh1** [comment]
Need verification as to which object lock mode we want (governance or compliance)

**Comment by JeffreyHuynh1** [comment]
You can't enable object lock if the bucket is already created, need to initialize this upon bucket creation
