### ISSUE TITLE
Move bucket automation script to OSIM Deployment repo 

### ISSUE THREAD

**Issue by StrayCat1** [cedardevs/onestop-clients#27]
Moving this - 
https://github.com/cedardevs/onestop-clients/blob/master/onestop-python-client/bucket_automation.py

Into this- 
https://github.com/cedardevs/osim-deployment

**Comment by StrayCat1** [comment]
https://github.com/cedardevs/osim-deployment/pull/1

**Comment by kenhtanaka** [comment]
Confirmed story can be closed
