### ISSUE TITLE
Avro schema follow up

### ISSUE THREAD

**Issue by StrayCat1** [cedardevs/onestop-clients#41]
We need to keep the python classes synced up to the schemas repo. So when the schemas change, the python classes are up to date. 

This will involve either
1) packaging the schemas up in a tar and including them as a dependency for the python library
2) generate the classes and check them into the schemas repo, publish them with pip, and include them as a dependency in the onestop python library

This may involve manually adding the import statements to the generated classes.

**Comment by erinreeves** [comment]
Resolved by OneStop story 1440
